### PR TITLE
IP bug fixed

### PR DESCRIPTION
**Pull request by ap1809**
Hi codehackerone ,IP bug fixed.

### CODE REVIEW

**Comment by ap1809** [comment]
Linked issue #13

**Review by Codehackerone — APPROVED** [review]
Looks perfect.

**Comment by Codehackerone** [comment]
How did you do that so fast? 🫣

**Comment by ap1809** [comment]
I had fixed a similar type of bug few days back.

**Comment by Codehackerone** [comment]
Cool.

**Comment by Codehackerone** [comment]
I see `response.data.city` did the trick. Great work bro!!

**Pull request merged**
