### PR TITLE
Navbar Redesigned 

### PR DESCRIPTION
**Pull request by mustafaazad03**
image
#34 Issue Fixed and Navbar Look Like This.

### CODE REVIEW

**Comment by mustafaazad03** [comment]
Please Merge This Changes .

**Review by Codehackerone — CHANGES_REQUESTED** [review]
Please make sure all of the previous navbar items are present, and are properly linked

**Comment by mustafaazad03** [comment]
Yah all items are linked !

**Review by Codehackerone — APPROVED** [review]
Good Work!!

**Comment by Codehackerone** [comment]
Tell me if number of Prs updated in hacktober profile

**Comment by mustafaazad03** [comment]
Thank you sir I will inform you 😃👍🏻

**Pull request merged**
